### PR TITLE
Change for new kind of Systems

### PR DESCRIPTION
**Pull request by Hedrauta**
Changed several things:

- Added new ressistancesystems and weaknesssystems to systemTypeScripts (got that one on the third push)
- Added Shield Ionizer & Hull Polarizer to systemTypeNames (yay.... new System-Upgrades)
- Added locale for designation of Hull Polarizers (there are several types)
- Changed name from “Defense Weapon System DWS-*num*” to “Internal Weapon Defense 0Weapon System IDWS-*num*” (meh.... but it also worked without the change 😜)

Oh.... and probably there isn't any shield booster anymore..... 

Maybe you'll make more tweaks or changes, but that one got me mad on research-stations 😉

### CODE REVIEW

**Comment by rinart73** [comment]
There was no need to add multiple Hull Polarizer entries, nor to define a `designation` variable. Those entries are only for displaying systems in the UI, so this would suffice:
```lua
"W-${designation}-Hull Polarizer ${rarity}"%_t % {designation = "X", rarity = "X"}
```
Also it's very important to have the list of upgrades display names (on client side) and the list of upgrades file names (on server side) in the same order.

And in the end, while I appreciate pull requests, I'm not going to change the mod id.

**Comment by Hedrauta** [comment]
😉 i had changed it for me, so it differs from the original one. 
Played with a friend on a dedicated server.... so thats why i had changed it

**Comment by rinart73** [comment]
In current mod version all system upgrades are detected automatically. It's still possible to adjust their name, if you wish.

**Comment by Hedrauta** [comment]
nah.... i'm fine.... btw... this was a year ago 😉  will use the original mod if i play avorion again 👍

**Pull request closed without merging**
